---
apiVersion: v1
kind: Service
metadata:
  name: mytun
  namespace: default
  labels:
    app: mytun
spec:
  type: ClusterIP
  selector:
    app: mytun
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-socket
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http-public